import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [currentSlide, setCurrentSlide] = useState(0);
  return (
    <div>
      <Head>
        <title>캐러셀 구현</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <div className={styles.carouselWrapper}>
          <div
            style={{ transform: `translateX(${(0 - currentSlide) * 100}%)` }}
            id={styles.first}
            className={`${styles.slide}`}
          >
            1
          </div>
          <div
            style={{ transform: `translateX(${(1 - currentSlide) * 100}%)` }}
            id={styles.second}
            className={`${styles.slide}`}
          >
            2
          </div>
          <div
            style={{ transform: `translateX(${(2 - currentSlide) * 100}%)` }}
            id={styles.third}
            className={`${styles.slide}`}
          >
            3
          </div>
          <div
            style={{ transform: `translateX(${(3 - currentSlide) * 100}%)` }}
            id={styles.forth}
            className={`${styles.slide}`}
          >
            4
          </div>
        </div>
        <input
          type="button"
          onClick={() =>
            setCurrentSlide((prev) => {
              if (prev > 0) {
                return prev - 1;
              } else {
                return 3;
              }
            })
          }
          value="<="
        />
        <input
          type="button"
          onClick={() =>
            setCurrentSlide((prev) => {
              if (prev < 3) {
                return prev + 1;
              } else {
                return 0;
              }
            })
          }
          value="=>"
        />
      </div>
    </div>
  );
};

export default Home;
